- group_id: albums
  listset:
    - id: game_decision
      listname: DECISION
      tags:
        - DECISION
    - id: game_rpg
      listname: RPG
      tags:
        - RPG
    - id: game_baroque
      listname: "バロックの城"
      tags:
        - "バロック"
    - id: game_renai
      listname: "夏の恋、いつものキミ"
      tags:
        - "夏恋"
    - id: game_wafu
      listname: "和風短編曲集"
      tags:
        - "和風短編曲集"
    - id: game_aquacocktail
      listname: "アクア カクテル"
      tags:
        - "アクア カクテル"
    - id: game_detective
      listname: "探偵 中園エイジ"
      tags:
        - "探偵"
    - id: game_horror
      listname: "時の館"
      tags:
        - "時の館"
    - id: game_planet
      listname: "エレクトロン"
      tags:
        - "エレクトロン"
    - id: game_lastmonth
      listname: "Last Month"
      tags:
        - "Last Month"
    - id: game_cover
      listname: "ゲーム音楽カバー"
      tags:
        - "ゲーム音楽カバー"
    - id: game_other
      listname: "その他"
      tags:
        - "その他"
- group_id: scenes
  listset:
    - id: scene_cheerful
      listname: "明るい"
      tags:
        - "明るい"
    - id: scene_dark
      listname: "暗い・悲しい"
      tags:
        - "暗い"
    - id: scene_honobono
      listname: "穏やか・安らぎ"
      tags:
        - "穏やか"
    - id: scene_grandeur
      listname: "壮大"
      tags:
        - "壮大"
    - id: scene_mysterious
      listname: "神秘的"
      tags:
        - "神秘的"
    - id: scene_speedy
      listname: "疾走感"
      tags:
        - "疾走感"
    - id: scene_tense
      listname: "緊張感"
      tags:
        - "緊張感"
    - id: scene_night
      listname: "夜"
      tags:
        - "夜"
    - id: scene_cyber
      listname: "サイバー"
      tags:
        - "サイバー"
    - id: scene_piano
      listname: "ピアノ"
      tags:
        - "ピアノ"
    - id: scene_battle
      listname: "バトル"
      tags:
        - "バトル"
    - id: scene_opening
      listname: "オープニング"
      tags:
        - "オープニング"
    - id: scene_ending
      listname: "エンディング"
      tags:
        - "エンディング"
    - id: scene_8bit
      listname: 8bit
      tags:
        - 8bit
